version: '3.9'

services:
#  app:
#    container_name: app
#    restart: always
#    command: python3 main.py
#    env_file: .env
#    build:
#      context: ./app
#      dockerfile: app.dockerfile
#    depends_on:
#      - db
#    ports:
#      - 8000:8000
    # expose:
    #   - 8000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      - ./front_vite/dist:/etc/nginx/dist/front
      # - ./static:/etc/nginx/static_img
    ports:
      - 80:80
      - 443:443

  # db:
  #   container_name: database
  #   image: postgres:latest
  #   env_file: db.env
  #   healthcheck:
  #     test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DBUSER} -d ${DBNAME}'" ]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 10
  #   volumes:
  #     - ./db-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432